Using custom data configuration default-6045b6d859a6831d
Reusing dataset csv (/home/sepehr8/.cache/huggingface/datasets/csv/default-6045b6d859a6831d/0.0.0/6b9057d9e23d9d8a2f05b985917a0da84d70c5dae3d22ddd8a3f22fb01c69d9e)
  0%|          | 0/1 [00:00<?, ?it/s]100%|██████████| 1/1 [00:03<00:00,  3.13s/it]100%|██████████| 1/1 [00:03<00:00,  3.13s/it]
Using custom data configuration default-e9ddb0055ee704dc
Reusing dataset csv (/home/sepehr8/.cache/huggingface/datasets/csv/default-e9ddb0055ee704dc/0.0.0/6b9057d9e23d9d8a2f05b985917a0da84d70c5dae3d22ddd8a3f22fb01c69d9e)
  0%|          | 0/1 [00:00<?, ?it/s]100%|██████████| 1/1 [00:00<00:00,  2.48it/s]100%|██████████| 1/1 [00:00<00:00,  2.48it/s]
  0%|          | 0/625 [00:00<?, ?ba/s]Ignored unknown kwarg option direction
Ignored unknown kwarg option direction
  0%|          | 1/625 [00:00<07:21,  1.41ba/s]Ignored unknown kwarg option direction
Ignored unknown kwarg option direction
  0%|          | 2/625 [00:01<06:59,  1.48ba/s]Ignored unknown kwarg option direction
Ignored unknown kwarg option direction
  0%|          | 3/625 [00:02<07:18,  1.42ba/s]Ignored unknown kwarg option direction
Ignored unknown kwarg option direction
  1%|          | 4/625 [00:02<07:16,  1.42ba/s]Ignored unknown kwarg option direction
Ignored unknown kwarg option direction
  1%|          | 5/625 [00:03<07:05,  1.46ba/s]Ignored unknown kwarg option direction
Ignored unknown kwarg option direction
  1%|          | 6/625 [00:04<07:54,  1.30ba/s]Ignored unknown kwarg option direction
Ignored unknown kwarg option direction
  1%|          | 7/625 [00:05<09:01,  1.14ba/s]Ignored unknown kwarg option direction
Ignored unknown kwarg option direction
  1%|          | 7/625 [00:06<09:06,  1.13ba/s]
Traceback (most recent call last):
  File "/project/6025819/sepehr8/test_generation/BART_test_generation/ENV/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 2498, in _map_single
    writer.write_batch(batch)
  File "/project/6025819/sepehr8/test_generation/BART_test_generation/ENV/lib/python3.8/site-packages/datasets/arrow_writer.py", line 499, in write_batch
    self.write_table(pa_table, writer_batch_size)
  File "/project/6025819/sepehr8/test_generation/BART_test_generation/ENV/lib/python3.8/site-packages/datasets/arrow_writer.py", line 516, in write_table
    self.pa_writer.write_batch(batch)
  File "pyarrow/ipc.pxi", line 384, in pyarrow.lib._CRecordBatchWriter.write_batch
  File "pyarrow/error.pxi", line 112, in pyarrow.lib.check_status
OSError: [Errno 122] Error writing bytes to file. Detail: [errno 122] Disk quota exceeded

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "BART_BPE.py", line 49, in <module>
    tokenized_train_dataset_word = train_dataset.map(tokenize_function, batched=True)
  File "/project/6025819/sepehr8/test_generation/BART_test_generation/ENV/lib/python3.8/site-packages/datasets/dataset_dict.py", line 494, in map
    {
  File "/project/6025819/sepehr8/test_generation/BART_test_generation/ENV/lib/python3.8/site-packages/datasets/dataset_dict.py", line 495, in <dictcomp>
    k: dataset.map(
  File "/project/6025819/sepehr8/test_generation/BART_test_generation/ENV/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 2102, in map
    return self._map_single(
  File "/project/6025819/sepehr8/test_generation/BART_test_generation/ENV/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 518, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/project/6025819/sepehr8/test_generation/BART_test_generation/ENV/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 485, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/project/6025819/sepehr8/test_generation/BART_test_generation/ENV/lib/python3.8/site-packages/datasets/fingerprint.py", line 413, in wrapper
    out = func(self, *args, **kwargs)
  File "/project/6025819/sepehr8/test_generation/BART_test_generation/ENV/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 2504, in _map_single
    writer.finalize()
  File "/project/6025819/sepehr8/test_generation/BART_test_generation/ENV/lib/python3.8/site-packages/datasets/arrow_writer.py", line 533, in finalize
    self.stream.close()
  File "pyarrow/io.pxi", line 173, in pyarrow.lib.NativeFile.close
  File "pyarrow/error.pxi", line 114, in pyarrow.lib.check_status
OSError: error closing file
